"""add_annotation_edits

Revision ID: 2708bbd83100
Revises: 7e463b9b7f14
Create Date: 2026-05-17 11:46:19.077646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2708bbd83100'
down_revision: Union[str, None] = '7e463b9b7f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_edits',
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('category_token', sa.String(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['category_token'], ['categories.token'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('token')
    )
    op.create_table('annotation_edits',
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('base_token', sa.String(), nullable=True),
        sa.Column('edit_type', sa.String(), nullable=False),
        sa.Column('sample_token', sa.String(), nullable=True),
        sa.Column('instance_token', sa.String(), nullable=True),
        sa.Column('translation', sa.JSON(), nullable=True),
        sa.Column('rotation', sa.JSON(), nullable=True),
        sa.Column('size', sa.JSON(), nullable=True),
        sa.Column('prev', sa.String(), nullable=True),
        sa.Column('next', sa.String(), nullable=True),
        sa.Column('visibility_token', sa.String(), nullable=True),
        sa.Column('attribute_tokens', sa.JSON(), nullable=True),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['base_token'], ['sample_annotations.token'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['sample_token'], ['samples.token'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['visibility_token'], ['visibilities.token'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_annotation_edits_base_token'), 'annotation_edits', ['base_token'], unique=False)
    op.create_index(op.f('ix_annotation_edits_instance_token'), 'annotation_edits', ['instance_token'], unique=False)
    op.create_index(op.f('ix_annotation_edits_sample_token'), 'annotation_edits', ['sample_token'], unique=False)
    # マージ処理で頻繁に使う複合インデックス (autogenerate では生成されないので手動追加)
    op.create_index('ix_annotation_edits_sample_edit_type', 'annotation_edits', ['sample_token', 'edit_type'], unique=False)
    


def downgrade() -> None:
    op.drop_index('ix_annotation_edits_sample_edit_type', table_name='annotation_edits')
    op.drop_index(op.f('ix_annotation_edits_sample_token'), table_name='annotation_edits')
    op.drop_index(op.f('ix_annotation_edits_instance_token'), table_name='annotation_edits')
    op.drop_index(op.f('ix_annotation_edits_base_token'), table_name='annotation_edits')
    op.drop_table('annotation_edits')
    op.drop_table('instance_edits')
