"""initial

Revision ID: 963888f6e306
Revises: 
Create Date: 2026-04-11 08:34:29.190845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '963888f6e306'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('categories',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('drivable_areas',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('polygon_tokens', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_drivable_areas_geom', 'drivable_areas', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('ego_poses',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('translation', sa.JSON(), nullable=False),
    sa.Column('rotation', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('logs',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('logfile', sa.String(), nullable=False),
    sa.Column('vehicle', sa.String(), nullable=False),
    sa.Column('date_captured', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('map_lines',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_map_lines_geom', 'map_lines', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('map_meta',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('canvas_edge', sa.JSON(), nullable=False),
    sa.Column('basemap_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('map_polygons',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_map_polygons_geom', 'map_polygons', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('sensors',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('modality', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('visibilities',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('calibrated_sensors',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('sensor_token', sa.String(), nullable=False),
    sa.Column('translation', sa.JSON(), nullable=False),
    sa.Column('rotation', sa.JSON(), nullable=False),
    sa.Column('camera_intrinsic', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_token'], ['sensors.token'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('instances',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('category_token', sa.String(), nullable=False),
    sa.Column('nbr_annotations', sa.Integer(), nullable=False),
    sa.Column('first_annotation_token', sa.String(), nullable=True),
    sa.Column('last_annotation_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_token'], ['categories.token'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['first_annotation_token'], ['sample_annotations.token'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['last_annotation_token'], ['sample_annotations.token'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('lane_connectors',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('polygon_token', sa.String(), nullable=True),
    sa.Column('arcline_path', sa.JSON(), nullable=False),
    sa.Column('incoming_tokens', sa.JSON(), nullable=True),
    sa.Column('outgoing_tokens', sa.JSON(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['polygon_token'], ['map_polygons.token'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_lane_connectors_geom', 'lane_connectors', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('lane_dividers',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('line_token', sa.String(), nullable=False),
    sa.Column('lane_divider_segments', sa.JSON(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['line_token'], ['map_lines.token'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_lane_dividers_geom', 'lane_dividers', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('lanes',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('polygon_token', sa.String(), nullable=False),
    sa.Column('lane_type', sa.String(), nullable=False),
    sa.Column('from_edge_line_token', sa.String(), nullable=True),
    sa.Column('to_edge_line_token', sa.String(), nullable=True),
    sa.Column('left_lane_divider_segments', sa.JSON(), nullable=True),
    sa.Column('right_lane_divider_segments', sa.JSON(), nullable=True),
    sa.Column('arcline_path', sa.JSON(), nullable=False),
    sa.Column('incoming_tokens', sa.JSON(), nullable=True),
    sa.Column('outgoing_tokens', sa.JSON(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['from_edge_line_token'], ['map_lines.token'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['polygon_token'], ['map_polygons.token'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_edge_line_token'], ['map_lines.token'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_lanes_geom', 'lanes', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('road_segments',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('polygon_token', sa.String(), nullable=False),
    sa.Column('is_intersection', sa.Boolean(), nullable=False),
    sa.Column('drivable_area_token', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['drivable_area_token'], ['drivable_areas.token'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['polygon_token'], ['map_polygons.token'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_road_segments_geom', 'road_segments', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('scenes',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('log_token', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nbr_samples', sa.Integer(), nullable=False),
    sa.Column('first_sample_token', sa.String(), nullable=False),
    sa.Column('last_sample_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['log_token'], ['logs.token'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('walkways',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('polygon_token', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['polygon_token'], ['map_polygons.token'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_walkways_geom', 'walkways', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('ped_crossings',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('polygon_token', sa.String(), nullable=False),
    sa.Column('road_segment_token', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['polygon_token'], ['map_polygons.token'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['road_segment_token'], ['road_segments.token'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_ped_crossings_geom', 'ped_crossings', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('road_blocks',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('polygon_token', sa.String(), nullable=False),
    sa.Column('from_edge_line_token', sa.String(), nullable=True),
    sa.Column('to_edge_line_token', sa.String(), nullable=True),
    sa.Column('road_segment_token', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['from_edge_line_token'], ['map_lines.token'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['polygon_token'], ['map_polygons.token'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['road_segment_token'], ['road_segments.token'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_edge_line_token'], ['map_lines.token'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_road_blocks_geom', 'road_blocks', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('road_dividers',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('line_token', sa.String(), nullable=False),
    sa.Column('road_segment_token', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['line_token'], ['map_lines.token'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['road_segment_token'], ['road_segments.token'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_road_dividers_geom', 'road_dividers', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('samples',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('scene_token', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('prev', sa.String(), nullable=True),
    sa.Column('next', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['next'], ['samples.token'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prev'], ['samples.token'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_token'], ['scenes.token'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('carpark_areas',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('polygon_token', sa.String(), nullable=False),
    sa.Column('orientation', sa.Float(), nullable=False),
    sa.Column('road_block_token', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['polygon_token'], ['map_polygons.token'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['road_block_token'], ['road_blocks.token'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_carpark_areas_geom', 'carpark_areas', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('sample_annotations',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('sample_token', sa.String(), nullable=False),
    sa.Column('instance_token', sa.String(), nullable=False),
    sa.Column('translation', sa.JSON(), nullable=False),
    sa.Column('rotation', sa.JSON(), nullable=False),
    sa.Column('size', sa.JSON(), nullable=False),
    sa.Column('prev', sa.String(), nullable=True),
    sa.Column('next', sa.String(), nullable=True),
    sa.Column('num_lidar_pts', sa.Integer(), nullable=False),
    sa.Column('num_radar_pts', sa.Integer(), nullable=False),
    sa.Column('visibility_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instance_token'], ['instances.token'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next'], ['sample_annotations.token'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prev'], ['sample_annotations.token'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_token'], ['samples.token'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visibility_token'], ['visibilities.token'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('sample_data',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('sample_token', sa.String(), nullable=False),
    sa.Column('calibrated_sensor_token', sa.String(), nullable=False),
    sa.Column('ego_pose_token', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('fileformat', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('is_key_frame', sa.Boolean(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('prev', sa.String(), nullable=True),
    sa.Column('next', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['calibrated_sensor_token'], ['calibrated_sensors.token'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ego_pose_token'], ['ego_poses.token'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['next'], ['sample_data.token'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prev'], ['sample_data.token'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_token'], ['samples.token'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('stop_lines',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('polygon_token', sa.String(), nullable=False),
    sa.Column('stop_line_type', sa.String(), nullable=False),
    sa.Column('road_block_token', sa.String(), nullable=True),
    sa.Column('ped_crossing_tokens', sa.JSON(), nullable=False),
    sa.Column('traffic_light_tokens', sa.JSON(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['polygon_token'], ['map_polygons.token'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['road_block_token'], ['road_blocks.token'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_stop_lines_geom', 'stop_lines', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('traffic_lights',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('line_token', sa.String(), nullable=False),
    sa.Column('traffic_light_type', sa.String(), nullable=False),
    sa.Column('from_road_block_token', sa.String(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('pose', sa.JSON(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['from_road_block_token'], ['road_blocks.token'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['line_token'], ['map_lines.token'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_traffic_lights_geom', 'traffic_lights', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('annotation_attributes',
    sa.Column('annotation_token', sa.String(), nullable=False),
    sa.Column('attribute_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_token'], ['sample_annotations.token'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attribute_token'], ['attributes.token'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('annotation_token', 'attribute_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation_attributes')
    op.drop_index('idx_traffic_lights_geom', table_name='traffic_lights', postgresql_using='gist')
    op.drop_table('traffic_lights')
    op.drop_index('idx_stop_lines_geom', table_name='stop_lines', postgresql_using='gist')
    op.drop_table('stop_lines')
    op.drop_table('sample_data')
    op.drop_table('sample_annotations')
    op.drop_index('idx_carpark_areas_geom', table_name='carpark_areas', postgresql_using='gist')
    op.drop_table('carpark_areas')
    op.drop_table('samples')
    op.drop_index('idx_road_dividers_geom', table_name='road_dividers', postgresql_using='gist')
    op.drop_table('road_dividers')
    op.drop_index('idx_road_blocks_geom', table_name='road_blocks', postgresql_using='gist')
    op.drop_table('road_blocks')
    op.drop_index('idx_ped_crossings_geom', table_name='ped_crossings', postgresql_using='gist')
    op.drop_table('ped_crossings')
    op.drop_index('idx_walkways_geom', table_name='walkways', postgresql_using='gist')
    op.drop_table('walkways')
    op.drop_table('scenes')
    op.drop_index('idx_road_segments_geom', table_name='road_segments', postgresql_using='gist')
    op.drop_table('road_segments')
    op.drop_index('idx_lanes_geom', table_name='lanes', postgresql_using='gist')
    op.drop_table('lanes')
    op.drop_index('idx_lane_dividers_geom', table_name='lane_dividers', postgresql_using='gist')
    op.drop_table('lane_dividers')
    op.drop_index('idx_lane_connectors_geom', table_name='lane_connectors', postgresql_using='gist')
    op.drop_table('lane_connectors')
    op.drop_table('instances')
    op.drop_table('calibrated_sensors')
    op.drop_table('visibilities')
    op.drop_table('sensors')
    op.drop_index('idx_map_polygons_geom', table_name='map_polygons', postgresql_using='gist')
    op.drop_table('map_polygons')
    op.drop_table('map_meta')
    op.drop_index('idx_map_lines_geom', table_name='map_lines', postgresql_using='gist')
    op.drop_table('map_lines')
    op.drop_table('logs')
    op.drop_table('ego_poses')
    op.drop_index('idx_drivable_areas_geom', table_name='drivable_areas', postgresql_using='gist')
    op.drop_table('drivable_areas')
    op.drop_table('categories')
    op.drop_table('attributes')
    # ### end Alembic commands ###
